basePath: /
definitions:
  controller.Peneliti:
    properties:
      _id:
        type: string
      jabatan:
        type: string
      jadwalpenelitian:
        type: string
      nama:
        type: string
      phone_number:
        type: string
    type: object
  controller.Presensi:
    properties:
      _id:
        type: string
      biodata:
        $ref: '#/definitions/controller.Peneliti'
      checkin:
        description: Datetime     primitive.DateTime `bson:"datetime,omitempty" json:"datetime,omitempty"`
        type: string
      location:
        type: string
      phone_number:
        type: string
    type: object
host: penelitian-tugas.herokuapp.com
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is a sample swagger for Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Fiber Example API
  version: "1.0"
paths:
  /semua:
    get:
      consumes:
      - application/json
      description: Mengambil semua data presensi.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Presensi'
      summary: Get All Data Presensi.
      tags:
      - semua
swagger: "2.0"
